### ISSUE TITLE
ServiceCollection 未包含AddRepository的定义

### ISSUE THREAD

**Issue by longletian** [a34546/Wei.Repository#4]
![image](https://user-images.githubusercontent.com/28197668/79050799-fce72c00-7c5e-11ea-8e26-fa584c1d3140.png)
 包也是一致的  就是不知道为什么我的就是会报未包含定义
![image](https://user-images.githubusercontent.com/28197668/79050820-20aa7200-7c5f-11ea-8f90-7645671c5615.png)

**Comment by a34546** [comment]
扩展方法，需要应用Wei.Repository

https://github.com/a34546/Wei.Repository/blob/master/src/Wei.Repository/Extensions/ServiceCollectionExtension.cs

**Comment by longletian** [comment]
好的  我找到了 感谢
